#!/usr/bin/env python

from Pipeline.producer_consumer_functions import producer, consumer
from Pipeline.pipeline import Pipeline 
import concurrent.futures
import logging


if __name__ == "__main__":
    format = "%(asctime)s: %(message)s"
    logging.basicConfig(format=format, level=logging.INFO, datefmt="%H:%M:%S")

    pipeline = Pipeline()

    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        executor.submit(producer, pipeline)
        executor.submit(consumer, pipeline)


